behaviors:
  AbilityChoose:
    trainer_type: ppo
    hyperparameters:
      batch_size: 10240
      buffer_size: 204800
      learning_rate: 0.000005
      beta: 0.001
      epsilon: 0.15
      lambd: 0.95
      num_epoch: 6
      learning_rate_schedule: linear
      beta_schedule: linear
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.975
        strength: 1.0
      curiosity:
        strength: 0.08
        gamma: 0.975
    max_steps: 500000000
    time_horizon: 64
    summary_freq: 500000